Play travis
Otus-DevOps-2021-05/DarkonGH_infra pull request #1
Opened 2021-06-25 18:05 UTC by DarkonGH

1. Не понимаю почему у меня не добавляется *Auto Assign Homework* в Actions. Просьба помочь.
2.  Очень много неточностей (не верные ссылки) в самом **дз_GitChatOps**, может это конечно так и задумано, но приходится искать, что писали другие в Cлаке.
3.  в самом **дз_GitChatOp**s как-то резки переходы между разделами, делаешь одно потом бамс уже другое. Нет смыслового перехода.
4. Совершенно не ясно где заполнять *Pull Request Template*, в ДЗ сказано куда положить, но в каком месте его заполнять не понятно. Если это шаблон то он должен быть каждый раз один и тот же, если каждый раз его редактировать под новое ДЗ то что с ним будет?
5. Не понятно работает и где работает установленный **re-commit**, когда он вызывается?

2021-06-25 20:21 UTC, Deron-D requested changes
.pre-commit-config.yaml вроде как бы должен быть в папке корневой репозитория, а не в папке .github, т.к. он предназначен для настройка хуков перед каждым коммитом.

2021-06-25 22:32 UTC, DarkonGH commented
перенес файл *.pre-commit-config.yaml* в корень проекта.

2021-06-26 07:21 UTC, Deron-D approved these changes
All right

2021-06-26 11:44 UTC, lackros commented
good work %)

2021-06-27 21:19 UTC, closed without merging

2021-06-28 06:27 UTC, DarkonGH commented
reopen